### ISSUE TITLE
wwwroot/installer doesn't exists

### ISSUE THREAD

**Issue by tsanyqudsi** [cloverstudio/Spika-Server#38]
i did everything on the build tutorial but i don't get the url

**Comment by Alexxandre3000** [comment]
Hello! I download Spika-Server but wwwroot/installer not existis in folder? Any send to me?
alexxandre3000@gmail.com tanks

**Comment by Jayuda** [comment]
Hello Mr @Alexxandre3000 : 
fix problem on ubuntu:
$ sudo a2enmod rewrite
$ sudo sed -i '/AllowOverride None/c AllowOverride All' /etc/apache2/sites-available/default
$ sudo service apache2 restart

its from @TTMTT and work for me
