### ISSUE TITLE
"Failed to install Spika backend. Please start again from here."  failed in step 3 running installer

### ISSUE THREAD

**Issue by zgao4** [cloverstudio/Spika-Server#68]
Hi there,

I am installing spika-server on ubuntu 14.04, following the instructions in http://www.spikaapp.com/en/build/server. 

When running http://server-ip/wwwroot/installer in a browser, it's ok

As shown in the pictures, it failed in step 3, "Create Initial Data". 

Can anybody help me?

**Comment by Alexxandre3000** [comment]
Hello! I download Spika-Server but wwwroot/installer not existis in folder? Any send to me?
alexxandre3000@gmail.com tanks

**Comment by ntkumaran** [comment]
Who are you

**Comment by Alexxandre3000** [comment]
I'm developer from Brazil!
